---
  - name: Ensure iterm2 is installed
    homebrew_cask:
      name: iterm2

  - name: Ensure console utils are installed
    homebrew:
      name:
        - bat
        - exa
        - fd
        - fzf
        - nvim
        - ripgrep

  - name: Ensure Node is installed
    homebrew:
      name:
        - node
